### ISSUE TITLE
Writing to deep nested file path throws error.

### ISSUE THREAD

**Issue by ming-codes** [rwjblue/broccoli-file-creator#3]
It happens in the test case too.

I modified the test case to `writeFile('/deep/nested/something.js', content)` and got this error:

```
  1) broccoli-file-creator creates the file specified:
     ENOENT: no such file or directory, symlink '/Users/mliu/Workspace/broccoli-file-creator/tmp/creator-cache_path-xjz8jf1O.tmp/deep/nested/something.js' -> '/Users/mliu/Workspace/broccoli-file-creator/tmp/creator-output_path-YgYkUrGV.tmp/deep/nested/something.js'
  Error: ENOENT: no such file or directory, symlink 'tmp/creator-cache_path-xjz8jf1O.tmp/deep/nested/something.js' -> '/Users/mliu/Workspace/broccoli-file-creator/tmp/creator-output_path-YgYkUrGV.tmp/deep/nested/something.js'
      at Error (native)
      at Object.fs.symlinkSync (fs.js:902:18)
      at symlink (node_modules/symlink-or-copy/index.js:82:14)
      at symlinkOrCopySync (node_modules/symlink-or-copy/index.js:58:5)
      at linkFromCache (index.js:43:3)
      at Creator.build (index.js:31:3)
      at node_modules/broccoli-plugin/read_compat.js:61:34
      at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:505:17)
      at node_modules/rsvp/dist/rsvp.js:1001:13
      at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by vitch** [comment]
I'm running into the same issue. Should this use case work (in which case I can try to provide a PR which creates the directory before symlinking) or is there another way to create a file in a folder which doesn't yet exist?

**Comment by stefanpenner** [comment]
sounds like a missing `mkdirp`

**Comment by vitch** [comment]
A little more info...

If `mkdirp.sync(path.dirname(to.outputFile));` is replaced with `mkdirp.sync(path.dirname(to));` on [line #41](https://github.com/rwjblue/broccoli-file-creator/blob/master/index.js#L41) then things seem to work as expected. 

Could this be down to differing versions of broccoli consuming the plugin or something?

**Comment by stefanpenner** [comment]
> Could this be down to differing versions of broccoli consuming the plugin or something?

i don't think so, sound like an isolated bug in this plugin. Care to submit a PR ?

**Comment by vitch** [comment]
Sure - no problem
