### ISSUE TITLE
this project appears to introduce 545 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/broccoli-file-creator#6]
I suspect this wasn't intended
## own files:
- [ ] tests 2

dependencies that may need to be investigated:
- [ ] broccoli-kitchen-sink-helpers      78
- [ ] broccoli-plugin     283 https://github.com/broccolijs/broccoli-plugin/issues/13
- [ ] broccoli-writer      77 <-- does't appear to be used by this project, but it is depended on
- [ ] mkdirp      45
- [ ] rsvp      39
- [ ] symlink-or-copy      11

**Comment by locks** [comment]
https://github.com/rwjblue/broccoli-file-creator/pull/7

**Comment by locks** [comment]
https://github.com/broccolijs/broccoli-kitchen-sink-helpers/pull/33 (merged)

**Comment by locks** [comment]
https://github.com/broccolijs/node-symlink-or-copy/pull/24 (merged)

**Comment by stefanpenner** [comment]
all extra deps have been removed
